name: Log New CodeWars Katas

on:
  workflow_dispatch:
  schedule:
    - cron: '30 17 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        env:
          CODEWARS_USERNAME: ${{ secrets.CODEWARS_USERNAME }}
          CODEWARS_EMAIL: ${{ secrets.CODEWARS_EMAIL }}
          CODEWARS_PASSWORD: ${{ secrets.CODEWARS_PASSWORD }}
        run: python main.py
        
      - name: Set Today's Date
        run: echo "TODAY=$(date +'%Y/%m/%d')" >> "$GITHUB_ENV"

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Add katas solved on ${{ env.TODAY }}"
          add: .
